# Generated by Django 3.2.6 on 2021-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upname', models.CharField(max_length=60)),
                ('upsign', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='allvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtitle', models.CharField(max_length=150)),
                ('vdesc', models.CharField(max_length=1500)),
            ],
        ),
    ]
